### ISSUE TITLE
S3 bucket name is not unique

### ISSUE THREAD

**Issue by tpark-itops** [jfrog/xray-aws-security-hub#27]
App fails to install w/ following error message:
- jfrog-xray-aws-failed-findings-dev-us-east-1 already exist

S3 bucket name is not unique. It's likely that the bucket name is used by someone else as there is not many permutations with three DeploymentEnvironment options. 

For the bucket name, please consider  
 **!Sub "jfrog-xray-aws-failed-findings-${AWS::Region}-${AWS::AccountId}-${DeploymentEnvironment}"**

**Comment by danielmkn** [comment]
@tpark-itops, thank you for the issue and the PR, the change will be released in v1.1.1
