### ISSUE TITLE
Security Hub findings for 2 resources created by the serverless app

### ISSUE THREAD

**Issue by leslie-corbalt** [jfrog/xray-aws-security-hub#30]
After deploying the` jfrog-xray-security-hub-integration — version 1.1.2` to my AWS account, I saw 2 Security Hub findings on the resources created by this application.

The Cloudformation Template has to be modified:
The DynamoDBTable needs to have point-in-time-recovery (PITR) enabled
The APIGateway stages (each of them) must have CloudWatch logs enabled. Make this a parameter to be filled in by the user. I set it to "Errors Only".

Details from Security Hub:

APIGateway.1 API Gateway REST and WebSocket API execution logging should be enabled
This control checks whether all stages of Amazon API Gateway REST and WebSocket APIs have logging enabled. The control fails if logging is not enabled for all methods of a stage or if the logging level is neither ERROR nor INFO.

DynamoDB.2 DynamoDB tables should have point-in-time recovery enabled
This control checks whether point-in-time recovery (PITR) is enabled for a DynamoDB table.

**Comment by danielmkn** [comment]
Thanks @leslie-corbalt, we will fix it.

**Comment by danielmkn** [comment]
Hi @leslie-corbalt! 
The fix is published in v1.1.3, thanks.
